'''
.. module:: everySNAKE
   :synopsis: Top level module containing the everySNAKE repository.

config.py : module 
    Tools for accessing the default directories that will be used for storage of permanent and temporary data generated by eS routines. Also includes (throttled) support for remote computations and parallel computation on the Broad's cluster.

coming soon: c
    *Plotting support (plot.py), Memory caching support (memo.py)*

.. moduleauthor:: Benjamin Holmes  <bh0085@gmail.com>
'''

import config
import utils
import peoplefuns
__all__ = ["config", "utils", "peoplefuns"]
