'''
Top level module containing the everySNAKE repository.

Contents:
config.py 
  Tools for accessing the default directories that will be used for storage of
permanent and temporary data generated by eS routines. Also includes (throttled)
support for remote computations and parallel computation on the Broad's cluster.


[Coming soon: Plotting support (plot.py), Memory caching support (memo.py)]

'''
