'''
Analyzes ezh2, finds conserved regions and aligns them to MBD.
'''

cons_ezh2 =     '''.MGQTGKKSEKGPlCWRKRVKSEYMRLRQLKRFRRADEVKoMFsoNRQKIhERTEhLNQEWKQRRIQPVHIhToVSSLpGhRECSVTSDlDFPtQVIPLKTLsAVASVPIMYSWSPLQQNFMVEDETVLHNIPaMGDEVLDpDGTFIEELIKNYDGKVHGDRECGFINDEIFVpLVNALsphpc..D.-Dstss.........................pEopP.R+FPuDKIFEAISSMFPDKGT.EELKEKYKELTEQQLPGALPPECTPNI..PNAKSVQREQSLHSFHTLFCRRCFKYDCFLH.....sFHAT.NTYKRKNsEsA.DsKPCGPpCYQhL.s...hc.hhhALhhph.Ko.stp.sscphG..sNNo.+sppPTlsVLE...+shspDhpA.spTuutsNshpc-E....so.SoEANSRC.TPIKMKPNIEPPENVEWsGAEAShFRVLIGTYYDNFCAIARLIGTKTCRQVYEFRVKESSIIAPs.sEDVDTPPRKK.RKHpLWAAHCRKIQLKKDGSSNHVYNYQPCDHP+QPCDSSCPCVIAQNFCEKFhQpSSECQNRFPGCRCKAQCNTKQCPCYLAVRECDPDLCLTCGAADHWDSKNhSsKNCSIQRGSKK..HL.LA.pshu....hlhDshpKN.chh.phhupIISQDEsDRRGKVYDKYMCSFLFNLNNsFVVDATpKGNKIRFANHSVNPNCYAKVhMVNGDHRIGIFAKhAIQTGEELFFDY.RYSQADALKYlGIEREMEIP'''
def run0():
    pass

